### ISSUE TITLE
Failed to install on Windows 7 with Python 3.4

### ISSUE THREAD

**Issue by Dwayne661** [coddingtonbear/python-myfitnesspal#24]
This is a fantastic module to discover and I would really like to use it. Unfortunately I am noob when it comes to installing 3rd party software so I am not sure what went wrong (or how to describe it to you). As far as I can tell, I was missing lxml so I installed that but the "import lxml.html" line still failed. If you can tell me how to report my problems in a way you can follow then I will give you all the details you want. 

Ben kilgore661@gmail.com

**Comment by coddingtonbear** [comment]
Ahh, Windows, well, you may be in for an adventure.  The setup *should* try to install them automatically for you, but installing dev-y things on Windows is always going to be a little bit like trying to launch the space shuttle from a gravel airstrip.

You might find luck by following the instructions here: http://lxml.de/installation.html, but if I were you, I'd really consider installing Cygwin (or, even better, in a VM -- but that's even more inconvenient) -- and then you'll at least have a unix-like environment in which to run things.  I know that kind of sucks, so I don't blame you if you try to avoid it.

Good luck, @dwayne661, and feel free to hop onto the [gitter channel](https://gitter.im/coddingtonbear/python-myfitnesspal) if you need one-on-one help, but it has been more than five years since I've last done any sort of development on Windows, so I'm not sure I'd be so much help.
