### ISSUE TITLE
get_measurements() broken

### ISSUE THREAD

**Issue by mtthwsar** [coddingtonbear/python-myfitnesspal#63]
client.get_measurements('Weight') has recently started returning empty.

**Comment by coddingtonbear** [comment]
Ahh!  Unfortunately, this library relies upon scraping the MFP website to return to you the necessary data, so things very often break when UI changes are made to the website.  Would you mind filing a pull request fixing the scraper?

**Comment by mtthwsar** [comment]
Hey Adam,

Thanks for the quick reply, I’ll take a look at it late this week and see if I can figure out what the issue was.

Adam

**Comment by zagi** [comment]
Hi Guys,
I think this one relates to something other because the UI didn't change. I've made an investigation and seems that it loses the session after first _get_document_for_url() method is called(the one which is responsible for getting the select options). When next _get_document_for_url() call is made the HTML returned don't contain the check-in table, but login wrapper. When I reset the session and login again like that:
```
self.session = requests.Session()
self._login()
```
at the beginning of while loop, it returns data as it should.

Maybe it's related to this:
![image](https://user-images.githubusercontent.com/4582196/39814946-b1b229c6-5396-11e8-98e7-9e3505bdbbe0.png)

Anyway, I'll prepare fix and PR it to master.

Mike

**Comment by zagi** [comment]
No fix is required. 
I've done all of my tests using `requests-2.11.1`, after upgrading it to `requests-2.18.4` everything works as expected. 
Any version of requests package lower than `2.17.0` doesn't work.

**Comment by coddingtonbear** [comment]
thanks @zagi!
